# Site settings
title: Bryan Hundven's site
email: bryanhundven@gmail.com
description: "Random docs and ramblings"
baseurl: ""
url: "http://bhundven.github.io"
twitter_username: bryanhundven
linkedin_username: bryanhundven
github_username:  bhundven

# Build settings
lsi: false
markdown: kramdown
permalink: /:year/:month/:day/:title.html
